### ISSUE TITLE
URL 编解码问题

### ISSUE THREAD

**Issue by chenlele-cll** [hujianzhe/util#2]
原 url = “http://metric01.b2030.host:3000/d/n0a2p9NSz/rdns-metric?orgId=1&var-app_channel=All&var-rdns_version=All&from=now-7d&to=now”

编解码出错

[2024-03-31 23:08:36] [thread 3714790] [--I--] [urlUtilsTest::14] URL encode = 173, http%3A%2F%2Fmetric01%2Eb2030%2Ehost%3A3000%2Fd%2Fn0a2p9NSz%2Frdns%2Dmetric%3ForgId%3D1%26var%2Dapp%5Fchannel%3DAll%26var%2Drdns%5Fversion%3DAll%26from%3Dnow%2D7d%26to%3Dnow
[2024-03-31 23:08:36] [thread 3714790] [--I--] [urlUtilsTest::18] URL decode = 123, http���metric01�b2030�host�3000�d�n0a2p9NSz�rdns�metric�orgId�1&var�app�channel�All&var�rdns�version�All&from�now�7d&to�now

**Comment by hujianzhe** [comment]
感谢~，目前已修复，错误原因是把ascii字母转回小写后又重复减去了‘A’的值。
#include "../workspace/util/inc/all.h"
#include <stdio.h>

int main() {
    const char url[] = "http://metric01.b2030.host:3000/d/n0a2p9NSz/rdns-metric?orgId=1&var-app_channel=All&var-rdns
_version=All&from=now-7d&to=now";
    printf("raw url_sz = %zu\n", sizeof(url) - 1);
    printf("raw url_str: %s\n", url);

    unsigned int encode_sz = urlEncode(url, sizeof(url) - 1, NULL);
    printf("encode_sz = %u\n", encode_sz);
    char* encode_str = (char*)malloc(encode_sz + 1);
    urlEncode(url, sizeof(url) - 1, encode_str);
    printf("encode_str: %s\n", encode_str);

    unsigned int decode_sz = urlDecode(encode_str, encode_sz, NULL);
    printf("decode_sz = %u\n", decode_sz);
    char* decode_str = (char*)malloc(decode_sz + 1);
    urlDecode(encode_str, encode_sz, decode_str);
    printf("decode_str: %s\n", decode_str);

    if (0 == strcmp(decode_str, url)) {
        puts("url equal ... success");
    }
    else {
        puts("url isn't equal");
    }

    free(encode_str);
    free(decode_str);
    return 0;
}

**Comment by hujianzhe** [comment]
感谢~此问题修复了，原因是解码时，如果是如果不是数字的ascii，会多减去了‘A’的值，但那个宏操作已经减去了‘a’的值
这是我的代码：
`#include "../workspace/util/inc/all.h"
#include <stdio.h>

int main() {
    const char url[] = "http://metric01.b2030.host:3000/d/n0a2p9NSz/rdns-metric?orgId=1&var-app_channel=All&var-rdns
_version=All&from=now-7d&to=now";
    printf("raw url_sz = %zu\n", sizeof(url) - 1);
    printf("raw url_str: %s\n", url);

    unsigned int encode_sz = urlEncode(url, sizeof(url) - 1, NULL);
    printf("encode_sz = %u\n", encode_sz);
    char* encode_str = (char*)malloc(encode_sz + 1);
    urlEncode(url, sizeof(url) - 1, encode_str);
    printf("encode_str: %s\n", encode_str);

    unsigned int decode_sz = urlDecode(encode_str, encode_sz, NULL);
    printf("decode_sz = %u\n", decode_sz);
    char* decode_str = (char*)malloc(decode_sz + 1);
    urlDecode(encode_str, encode_sz, decode_str);
    printf("decode_str: %s\n", decode_str);

    if (0 == strcmp(decode_str, url)) {
        puts("url equal ... success");
    }
    else {
        puts("url isn't equal");
    }

    free(encode_str);
    free(decode_str);
    return 0;
}`

这是现在的输出：
raw url_sz = 123
raw url_str: http://metric01.b2030.host:3000/d/n0a2p9NSz/rdns-metric?orgId=1&var-app_channel=All&var-rdns_version=All&fr
om=now-7d&to=now
encode_sz = 173
encode_str: http%3A%2F%2Fmetric01%2Eb2030%2Ehost%3A3000%2Fd%2Fn0a2p9NSz%2Frdns%2Dmetric%3ForgId%3D1%26var%2Dapp%5Fchanne
l%3DAll%26var%2Drdns%5Fversion%3DAll%26from%3Dnow%2D7d%26to%3Dnow
decode_sz = 123
decode_str: http://metric01.b2030.host:3000/d/n0a2p9NSz/rdns-metric?orgId=1&var-app_channel=All&var-rdns_version=All&fro
m=now-7d&to=now
url equal ... success
